export interface ComunaData {
  comuna: string;
  region: string;
}

export const COMUNAS_CHILE: ComunaData[] = [
  { comuna: "Arica", region: "Arica y Parinacota" },
  { comuna: "Camarones", region: "Arica y Parinacota" },
  { comuna: "Putre", region: "Arica y Parinacota" },
  { comuna: "General Lagos", region: "Arica y Parinacota" },
  { comuna: "Iquique", region: "Tarapacá" },
  { comuna: "Alto Hospicio", region: "Tarapacá" },
  { comuna: "Pozo Almonte", region: "Tarapacá" },
  { comuna: "Camiña", region: "Tarapacá" },
  { comuna: "Colchane", region: "Tarapacá" },
  { comuna: "Huara", region: "Tarapacá" },
  { comuna: "Pica", region: "Tarapacá" },
  { comuna: "Antofagasta", region: "Antofagasta" },
  { comuna: "Mejillones", region: "Antofagasta" },
  { comuna: "Sierra Gorda", region: "Antofagasta" },
  { comuna: "Taltal", region: "Antofagasta" },
  { comuna: "Calama", region: "Antofagasta" },
  { comuna: "Ollagüe", region: "Antofagasta" },
  { comuna: "San Pedro de Atacama", region: "Antofagasta" },
  { comuna: "Tocopilla", region: "Antofagasta" },
  { comuna: "María Elena", region: "Antofagasta" },
  { comuna: "Copiapó", region: "Atacama" },
  { comuna: "Caldera", region: "Atacama" },
  { comuna: "Tierra Amarilla", region: "Atacama" },
  { comuna: "Chañaral", region: "Atacama" },
  { comuna: "Diego de Almagro", region: "Atacama" },
  { comuna: "Vallenar", region: "Atacama" },
  { comuna: "Alto del Carmen", region: "Atacama" },
  { comuna: "Freirina", region: "Atacama" },
  { comuna: "Huasco", region: "Atacama" },
  { comuna: "La Serena", region: "Coquimbo" },
  { comuna: "Coquimbo", region: "Coquimbo" },
  { comuna: "Andacollo", region: "Coquimbo" },
  { comuna: "La Higuera", region: "Coquimbo" },
  { comuna: "Paihuano", region: "Coquimbo" },
  { comuna: "Vicuña", region: "Coquimbo" },
  { comuna: "Illapel", region: "Coquimbo" },
  { comuna: "Canela", region: "Coquimbo" },
  { comuna: "Los Vilos", region: "Coquimbo" },
  { comuna: "Salamanca", region: "Coquimbo" },
  { comuna: "Ovalle", region: "Coquimbo" },
  { comuna: "Combarbalá", region: "Coquimbo" },
  { comuna: "Monte Patria", region: "Coquimbo" },
  { comuna: "Punitaqui", region: "Coquimbo" },
  { comuna: "Río Hurtado", region: "Coquimbo" },
  { comuna: "Valparaíso", region: "Valparaíso" },
  { comuna: "Casablanca", region: "Valparaíso" },
  { comuna: "Concón", region: "Valparaíso" },
  { comuna: "Juan Fernández", region: "Valparaíso" },
  { comuna: "Puchuncaví", region: "Valparaíso" },
  { comuna: "Quintero", region: "Valparaíso" },
  { comuna: "Viña del Mar", region: "Valparaíso" },
  { comuna: "Isla de Pascua", region: "Valparaíso" },
  { comuna: "Los Andes", region: "Valparaíso" },
  { comuna: "Calle Larga", region: "Valparaíso" },
  { comuna: "Rinconada", region: "Valparaíso" },
  { comuna: "San Esteban", region: "Valparaíso" },
  { comuna: "La Ligua", region: "Valparaíso" },
  { comuna: "Cabildo", region: "Valparaíso" },
  { comuna: "Papudo", region: "Valparaíso" },
  { comuna: "Petorca", region: "Valparaíso" },
  { comuna: "Zapallar", region: "Valparaíso" },
  { comuna: "Quillota", region: "Valparaíso" },
  { comuna: "La Calera", region: "Valparaíso" },
  { comuna: "Hijuelas", region: "Valparaíso" },
  { comuna: "La Cruz", region: "Valparaíso" },
  { comuna: "Nogales", region: "Valparaíso" },
  { comuna: "San Antonio", region: "Valparaíso" },
  { comuna: "Algarrobo", region: "Valparaíso" },
  { comuna: "Cartagena", region: "Valparaíso" },
  { comuna: "El Quisco", region: "Valparaíso" },
  { comuna: "El Tabo", region: "Valparaíso" },
  { comuna: "Santo Domingo", region: "Valparaíso" },
  { comuna: "San Felipe", region: "Valparaíso" },
  { comuna: "Catemu", region: "Valparaíso" },
  { comuna: "Llay-Llay", region: "Valparaíso" },
  { comuna: "Panquehue", region: "Valparaíso" },
  { comuna: "Putaendo", region: "Valparaíso" },
  { comuna: "Santa María", region: "Valparaíso" },
  { comuna: "Quilpué", region: "Valparaíso" },
  { comuna: "Limache", region: "Valparaíso" },
  { comuna: "Olmué", region: "Valparaíso" },
  { comuna: "Villa Alemana", region: "Valparaíso" },
  { comuna: "Rancagua", region: "O'Higgins" },
  { comuna: "Codegua", region: "O'Higgins" },
  { comuna: "Coinco", region: "O'Higgins" },
  { comuna: "Coltauco", region: "O'Higgins" },
  { comuna: "Doñihue", region: "O'Higgins" },
  { comuna: "Graneros", region: "O'Higgins" },
  { comuna: "Las Cabras", region: "O'Higgins" },
  { comuna: "Machalí", region: "O'Higgins" },
  { comuna: "Malloa", region: "O'Higgins" },
  { comuna: "Mostazal", region: "O'Higgins" },
  { comuna: "Olivar", region: "O'Higgins" },
  { comuna: "Peumo", region: "O'Higgins" },
  { comuna: "Pichidegua", region: "O'Higgins" },
  { comuna: "Quinta de Tilcoco", region: "O'Higgins" },
  { comuna: "Rengo", region: "O'Higgins" },
  { comuna: "Requínoa", region: "O'Higgins" },
  { comuna: "San Vicente", region: "O'Higgins" },
  { comuna: "Pichilemu", region: "O'Higgins" },
  { comuna: "La Estrella", region: "O'Higgins" },
  { comuna: "Litueche", region: "O'Higgins" },
  { comuna: "Marchihue", region: "O'Higgins" },
  { comuna: "Navidad", region: "O'Higgins" },
  { comuna: "Paredones", region: "O'Higgins" },
  { comuna: "San Fernando", region: "O'Higgins" },
  { comuna: "Chépica", region: "O'Higgins" },
  { comuna: "Chimbarongo", region: "O'Higgins" },
  { comuna: "Lolol", region: "O'Higgins" },
  { comuna: "Nancagua", region: "O'Higgins" },
  { comuna: "Palmilla", region: "O'Higgins" },
  { comuna: "Peralillo", region: "O'Higgins" },
  { comuna: "Placilla", region: "O'Higgins" },
  { comuna: "Pumanque", region: "O'Higgins" },
  { comuna: "Santa Cruz", region: "O'Higgins" },
  { comuna: "Talca", region: "Maule" },
  { comuna: "Constitución", region: "Maule" },
  { comuna: "Curepto", region: "Maule" },
  { comuna: "Empedrado", region: "Maule" },
  { comuna: "Maule", region: "Maule" },
  { comuna: "Pelarco", region: "Maule" },
  { comuna: "Pencahue", region: "Maule" },
  { comuna: "Río Claro", region: "Maule" },
  { comuna: "San Clemente", region: "Maule" },
  { comuna: "San Rafael", region: "Maule" },
  { comuna: "Cauquenes", region: "Maule" },
  { comuna: "Chanco", region: "Maule" },
  { comuna: "Pelluhue", region: "Maule" },
  { comuna: "Curicó", region: "Maule" },
  { comuna: "Hualañé", region: "Maule" },
  { comuna: "Licantén", region: "Maule" },
  { comuna: "Molina", region: "Maule" },
  { comuna: "Rauco", region: "Maule" },
  { comuna: "Romeral", region: "Maule" },
  { comuna: "Sagrada Familia", region: "Maule" },
  { comuna: "Teno", region: "Maule" },
  { comuna: "Vichuquén", region: "Maule" },
  { comuna: "Linares", region: "Maule" },
  { comuna: "Colbún", region: "Maule" },
  { comuna: "Longaví", region: "Maule" },
  { comuna: "Parral", region: "Maule" },
  { comuna: "Retiro", region: "Maule" },
  { comuna: "San Javier", region: "Maule" },
  { comuna: "Villa Alegre", region: "Maule" },
  { comuna: "Yerbas Buenas", region: "Maule" },
  { comuna: "Chillán", region: "Ñuble" },
  { comuna: "Bulnes", region: "Ñuble" },
  { comuna: "Chillán Viejo", region: "Ñuble" },
  { comuna: "El Carmen", region: "Ñuble" },
  { comuna: "Pemuco", region: "Ñuble" },
  { comuna: "Pinto", region: "Ñuble" },
  { comuna: "Quillón", region: "Ñuble" },
  { comuna: "San Ignacio", region: "Ñuble" },
  { comuna: "Yungay", region: "Ñuble" },
  { comuna: "Quirihue", region: "Ñuble" },
  { comuna: "Cobquecura", region: "Ñuble" },
  { comuna: "Coelemu", region: "Ñuble" },
  { comuna: "Ninhue", region: "Ñuble" },
  { comuna: "Portezuelo", region: "Ñuble" },
  { comuna: "Ránquil", region: "Ñuble" },
  { comuna: "Treguaco", region: "Ñuble" },
  { comuna: "San Carlos", region: "Ñuble" },
  { comuna: "Coihueco", region: "Ñuble" },
  { comuna: "Ñiquén", region: "Ñuble" },
  { comuna: "San Fabián", region: "Ñuble" },
  { comuna: "San Nicolás", region: "Ñuble" },
  { comuna: "Concepción", region: "Biobío" },
  { comuna: "Coronel", region: "Biobío" },
  { comuna: "Chiguayante", region: "Biobío" },
  { comuna: "Florida", region: "Biobío" },
  { comuna: "Hualqui", region: "Biobío" },
  { comuna: "Lota", region: "Biobío" },
  { comuna: "Penco", region: "Biobío" },
  { comuna: "San Pedro de La Paz", region: "Biobío" },
  { comuna: "Santa Juana", region: "Biobío" },
  { comuna: "Talcahuano", region: "Biobío" },
  { comuna: "Tomé", region: "Biobío" },
  { comuna: "Hualpén", region: "Biobío" },
  { comuna: "Lebu", region: "Biobío" },
  { comuna: "Arauco", region: "Biobío" },
  { comuna: "Cañete", region: "Biobío" },
  { comuna: "Contulmo", region: "Biobío" },
  { comuna: "Curanilahue", region: "Biobío" },
  { comuna: "Los Álamos", region: "Biobío" },
  { comuna: "Tirúa", region: "Biobío" },
  { comuna: "Los Ángeles", region: "Biobío" },
  { comuna: "Antuco", region: "Biobío" },
  { comuna: "Cabrero", region: "Biobío" },
  { comuna: "Laja", region: "Biobío" },
  { comuna: "Mulchén", region: "Biobío" },
  { comuna: "Nacimiento", region: "Biobío" },
  { comuna: "Negrete", region: "Biobío" },
  { comuna: "Quilaco", region: "Biobío" },
  { comuna: "Quilleco", region: "Biobío" },
  { comuna: "San Rosendo", region: "Biobío" },
  { comuna: "Santa Bárbara", region: "Biobío" },
  { comuna: "Tucapel", region: "Biobío" },
  { comuna: "Yumbel", region: "Biobío" },
  { comuna: "Alto Biobío", region: "Biobío" },
  { comuna: "Temuco", region: "La Araucanía" },
  { comuna: "Carahue", region: "La Araucanía" },
  { comuna: "Cunco", region: "La Araucanía" },
  { comuna: "Curarrehue", region: "La Araucanía" },
  { comuna: "Freire", region: "La Araucanía" },
  { comuna: "Galvarino", region: "La Araucanía" },
  { comuna: "Gorbea", region: "La Araucanía" },
  { comuna: "Lautaro", region: "La Araucanía" },
  { comuna: "Loncoche", region: "La Araucanía" },
  { comuna: "Melipeuco", region: "La Araucanía" },
  { comuna: "Nueva Imperial", region: "La Araucanía" },
  { comuna: "Padre Las Casas", region: "La Araucanía" },
  { comuna: "Perquenco", region: "La Araucanía" },
  { comuna: "Pitrufquén", region: "La Araucanía" },
  { comuna: "Pucón", region: "La Araucanía" },
  { comuna: "Saavedra", region: "La Araucanía" },
  { comuna: "Teodoro Schmidt", region: "La Araucanía" },
  { comuna: "Toltén", region: "La Araucanía" },
  { comuna: "Vilcún", region: "La Araucanía" },
  { comuna: "Villarrica", region: "La Araucanía" },
  { comuna: "Cholchol", region: "La Araucanía" },
  { comuna: "Angol", region: "La Araucanía" },
  { comuna: "Collipulli", region: "La Araucanía" },
  { comuna: "Curacautín", region: "La Araucanía" },
  { comuna: "Ercilla", region: "La Araucanía" },
  { comuna: "Lonquimay", region: "La Araucanía" },
  { comuna: "Los Sauces", region: "La Araucanía" },
  { comuna: "Lumaco", region: "La Araucanía" },
  { comuna: "Purén", region: "La Araucanía" },
  { comuna: "Renaico", region: "La Araucanía" },
  { comuna: "Traiguén", region: "La Araucanía" },
  { comuna: "Victoria", region: "La Araucanía" },
  { comuna: "Valdivia", region: "Los Ríos" },
  { comuna: "Corral", region: "Los Ríos" },
  { comuna: "Lanco", region: "Los Ríos" },
  { comuna: "Los Lagos", region: "Los Ríos" },
  { comuna: "Máfil", region: "Los Ríos" },
  { comuna: "Mariquina", region: "Los Ríos" },
  { comuna: "Paillaco", region: "Los Ríos" },
  { comuna: "Panguipulli", region: "Los Ríos" },
  { comuna: "La Unión", region: "Los Ríos" },
  { comuna: "Futrono", region: "Los Ríos" },
  { comuna: "Lago Ranco", region: "Los Ríos" },
  { comuna: "Río Bueno", region: "Los Ríos" },
  { comuna: "Puerto Montt", region: "Los Lagos" },
  { comuna: "Calbuco", region: "Los Lagos" },
  { comuna: "Cochamó", region: "Los Lagos" },
  { comuna: "Fresia", region: "Los Lagos" },
  { comuna: "Frutillar", region: "Los Lagos" },
  { comuna: "Los Muermos", region: "Los Lagos" },
  { comuna: "Llanquihue", region: "Los Lagos" },
  { comuna: "Maullín", region: "Los Lagos" },
  { comuna: "Puerto Varas", region: "Los Lagos" },
  { comuna: "Castro", region: "Los Lagos" },
  { comuna: "Ancud", region: "Los Lagos" },
  { comuna: "Chonchi", region: "Los Lagos" },
  { comuna: "Curaco de Vélez", region: "Los Lagos" },
  { comuna: "Dalcahue", region: "Los Lagos" },
  { comuna: "Puqueldón", region: "Los Lagos" },
  { comuna: "Queilén", region: "Los Lagos" },
  { comuna: "Quellón", region: "Los Lagos" },
  { comuna: "Quemchi", region: "Los Lagos" },
  { comuna: "Quinchao", region: "Los Lagos" },
  { comuna: "Osorno", region: "Los Lagos" },
  { comuna: "Puerto Octay", region: "Los Lagos" },
  { comuna: "Purranque", region: "Los Lagos" },
  { comuna: "Puyehue", region: "Los Lagos" },
  { comuna: "Río Negro", region: "Los Lagos" },
  { comuna: "San Juan de la Costa", region: "Los Lagos" },
  { comuna: "San Pablo", region: "Los Lagos" },
  { comuna: "Chaitén", region: "Los Lagos" },
  { comuna: "Futaleufú", region: "Los Lagos" },
  { comuna: "Hualaihué", region: "Los Lagos" },
  { comuna: "Palena", region: "Los Lagos" },
  { comuna: "Coyhaique", region: "Aysén" },
  { comuna: "Lago Verde", region: "Aysén" },
  { comuna: "Aysén", region: "Aysén" },
  { comuna: "Cisnes", region: "Aysén" },
  { comuna: "Guaitecas", region: "Aysén" },
  { comuna: "Cochrane", region: "Aysén" },
  { comuna: "O'Higgins", region: "Aysén" },
  { comuna: "Tortel", region: "Aysén" },
  { comuna: "Chile Chico", region: "Aysén" },
  { comuna: "Río Ibáñez", region: "Aysén" },
  { comuna: "Punta Arenas", region: "Magallanes" },
  { comuna: "Laguna Blanca", region: "Magallanes" },
  { comuna: "Río Verde", region: "Magallanes" },
  { comuna: "San Gregorio", region: "Magallanes" },
  { comuna: "Cabo de Hornos", region: "Magallanes" },
  { comuna: "Antártica", region: "Magallanes" },
  { comuna: "Porvenir", region: "Magallanes" },
  { comuna: "Primavera", region: "Magallanes" },
  { comuna: "Timaukel", region: "Magallanes" },
  { comuna: "Natales", region: "Magallanes" },
  { comuna: "Torres del Paine", region: "Magallanes" },
  { comuna: "Santiago", region: "Metropolitana" },
  { comuna: "Cerrillos", region: "Metropolitana" },
  { comuna: "Cerro Navia", region: "Metropolitana" },
  { comuna: "Conchalí", region: "Metropolitana" },
  { comuna: "El Bosque", region: "Metropolitana" },
  { comuna: "Estación Central", region: "Metropolitana" },
  { comuna: "Huechuraba", region: "Metropolitana" },
  { comuna: "Independencia", region: "Metropolitana" },
  { comuna: "La Cisterna", region: "Metropolitana" },
  { comuna: "La Florida", region: "Metropolitana" },
  { comuna: "La Granja", region: "Metropolitana" },
  { comuna: "La Pintana", region: "Metropolitana" },
  { comuna: "La Reina", region: "Metropolitana" },
  { comuna: "Las Condes", region: "Metropolitana" },
  { comuna: "Lo Barnechea", region: "Metropolitana" },
  { comuna: "Lo Espejo", region: "Metropolitana" },
  { comuna: "Lo Prado", region: "Metropolitana" },
  { comuna: "Macul", region: "Metropolitana" },
  { comuna: "Maipú", region: "Metropolitana" },
  { comuna: "Ñuñoa", region: "Metropolitana" },
  { comuna: "Pedro Aguirre Cerda", region: "Metropolitana" },
  { comuna: "Peñalolén", region: "Metropolitana" },
  { comuna: "Providencia", region: "Metropolitana" },
  { comuna: "Pudahuel", region: "Metropolitana" },
  { comuna: "Quilicura", region: "Metropolitana" },
  { comuna: "Quinta Normal", region: "Metropolitana" },
  { comuna: "Recoleta", region: "Metropolitana" },
  { comuna: "Renca", region: "Metropolitana" },
  { comuna: "San Joaquín", region: "Metropolitana" },
  { comuna: "San Miguel", region: "Metropolitana" },
  { comuna: "San Ramón", region: "Metropolitana" },
  { comuna: "Vitacura", region: "Metropolitana" },
  { comuna: "Puente Alto", region: "Metropolitana" },
  { comuna: "Pirque", region: "Metropolitana" },
  { comuna: "San José de Maipo", region: "Metropolitana" },
  { comuna: "Colina", region: "Metropolitana" },
  { comuna: "Lampa", region: "Metropolitana" },
  { comuna: "Til Til", region: "Metropolitana" },
  { comuna: "San Bernardo", region: "Metropolitana" },
  { comuna: "Buin", region: "Metropolitana" },
  { comuna: "Calera de Tango", region: "Metropolitana" },
  { comuna: "Paine", region: "Metropolitana" },
  { comuna: "Melipilla", region: "Metropolitana" },
  { comuna: "Alhué", region: "Metropolitana" },
  { comuna: "Curacaví", region: "Metropolitana" },
  { comuna: "María Pinto", region: "Metropolitana" },
  { comuna: "San Pedro", region: "Metropolitana" },
  { comuna: "Talagante", region: "Metropolitana" },
  { comuna: "El Monte", region: "Metropolitana" },
  { comuna: "Isla de Maipo", region: "Metropolitana" },
  { comuna: "Padre Hurtado", region: "Metropolitana" },
  { comuna: "Peñaflor", region: "Metropolitana" },
];

export const REGIONES = Array.from(new Set(COMUNAS_CHILE.map((c) => c.region))).sort();
