import type { Evento } from "@/types/index";

export const mockEventos = [
{
_id: "1",
nombre: "Festival de Música Electrónica",
descripcion:
"El festival más grande de música electrónica del país. Más de 20 artistas internacionales, 3 escenarios y una experiencia inolvidable. Disfruta de sets de los mejores DJs del mundo en un ambiente único con efectos visuales de última generación.",
fecha: "2026-05-15",
hora: "18:00",
espacio: "Estadio Nacional",
precio: 1500,
categoria: "Música",
imagenUrl:
"https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=600&fit=crop",
capacidad: 50000,
entradasVendidas: 35000,
activo: true,
gratuito: false,
entradaLiberada: false,
esMultipleDias: false,
limitePorUsuario: 10,
permiteTransferencia: false,
entradaNominal: false,
codigosDescuento: [],
configEnvio: { envioAutomatico: true, permitirReenvio: true, emailAsistente: false },
tieneAsientos: false,
eliminado: false,
createdAt: "2026-01-01T00:00:00Z",
updatedAt: "2026-01-15T00:00:00Z",
},
{
_id: "2",
nombre: "Conferencia de Tecnología 2026",
descripcion:
"La conferencia más importante de tecnología e innovación. Ponentes de empresas como Google, Apple, Microsoft y startups emergentes compartirán sus visiones del futuro. Networking, talleres prácticos y exposición de nuevos productos.",
fecha: "2026-06-20",
hora: "09:00",
espacio: "Centro de Convenciones",
precio: 2500,
categoria: "Tecnología",
imagenUrl:
"https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop",
capacidad: 5000,
entradasVendidas: 4200,
activo: true,
gratuito: false,
entradaLiberada: false,
esMultipleDias: false,
limitePorUsuario: 10,
permiteTransferencia: false,
entradaNominal: false,
codigosDescuento: [],
configEnvio: { envioAutomatico: true, permitirReenvio: true, emailAsistente: false },
tieneAsientos: false,
eliminado: false,
createdAt: "2026-01-05T00:00:00Z",
updatedAt: "2026-01-20T00:00:00Z",
},
{
_id: "3",
nombre: "Exposición de Arte Moderno",
descripcion:
"Una colección exclusiva de más de 200 obras de artistas contemporáneos de Latinoamérica. Pinturas, esculturas e instalaciones interactivas que desafían los límites del arte tradicional.",
fecha: "2026-04-10",
hora: "10:00",
espacio: "Museo de Arte Contemporáneo",
precio: 350,
categoria: "Arte",
imagenUrl:
"https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=600&fit=crop",
capacidad: 1000,
entradasVendidas: 650,
activo: true,
gratuito: false,
entradaLiberada: false,
esMultipleDias: false,
limitePorUsuario: 10,
permiteTransferencia: false,
entradaNominal: false,
codigosDescuento: [],
configEnvio: { envioAutomatico: true, permitirReenvio: true, emailAsistente: false },
tieneAsientos: false,
eliminado: false,
createdAt: "2026-01-10T00:00:00Z",
updatedAt: "2026-01-25T00:00:00Z",
},
{
_id: "4",
nombre: "Maratón Ciudad 2026",
descripcion:
"El maratón más emblemático del país. 42 km de recorrido por las principales avenidas de la ciudad. Categorías para todos los niveles, desde principiantes hasta profesionales. Incluye kit de corredor y medalla finisher.",
fecha: "2026-07-05",
hora: "06:00",
espacio: "Ángel de la Independencia",
precio: 800,
categoria: "Deportes",
imagenUrl:
"https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?w=800&h=600&fit=crop",
capacidad: 30000,
entradasVendidas: 28500,
activo: true,
gratuito: false,
entradaLiberada: false,
esMultipleDias: false,
limitePorUsuario: 10,
permiteTransferencia: false,
entradaNominal: false,
codigosDescuento: [],
configEnvio: { envioAutomatico: true, permitirReenvio: true, emailAsistente: false },
tieneAsientos: false,
eliminado: false,
createdAt: "2026-01-15T00:00:00Z",
updatedAt: "2026-02-01T00:00:00Z",
},
{
_id: "5",
nombre: "Festival Gastronómico",
descripcion:
"Degusta los mejores platillos de más de 50 restaurantes reconocidos. Chefs de renombre internacional, catas de vino, clases de cocina en vivo y mucho más. Una experiencia culinaria única.",
fecha: "2026-08-12",
hora: "12:00",
espacio: "Parque Lincoln",
precio: 600,
categoria: "Gastronomía",
imagenUrl:
"https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop",
capacidad: 8000,
entradasVendidas: 5600,
activo: true,
gratuito: false,
entradaLiberada: false,
esMultipleDias: false,
limitePorUsuario: 10,
permiteTransferencia: false,
entradaNominal: false,
codigosDescuento: [],
configEnvio: { envioAutomatico: true, permitirReenvio: true, emailAsistente: false },
tieneAsientos: false,
eliminado: false,
createdAt: "2026-01-20T00:00:00Z",
updatedAt: "2026-02-05T00:00:00Z",
},
{
_id: "6",
nombre: "Concierto Sinfónico",
descripcion:
"La Orquesta Filarmónica presenta un concerto especial con las mejores obras de Beethoven y Mozart. Dirigido por el maestro Carlos Hernández con la participación de solistas internacionales.",
fecha: "2026-05-28",
hora: "20:00",
espacio: "Palacio de Bellas Artes",
precio: 1200,
categoria: "Música",
imagenUrl:
"https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&h=600&fit=crop",
capacidad: 2000,
entradasVendidas: 1850,
activo: true,
gratuito: false,
entradaLiberada: false,
esMultipleDias: false,
limitePorUsuario: 10,
permiteTransferencia: false,
entradaNominal: false,
codigosDescuento: [],
configEnvio: { envioAutomatico: true, permitirReenvio: true, emailAsistente: false },
tieneAsientos: false,
eliminado: false,
createdAt: "2026-01-25T00:00:00Z",
updatedAt: "2026-02-10T00:00:00Z",
},
] as unknown as Evento[];

export function getEventoById(id: string): Evento | undefined {
  return mockEventos.find((evento) => evento._id === id);
}
